output-format: json

strictness: medium
test-warnings: true
doc-warnings: false

ignore-paths:
  - docs

ignore-patterns:
  - (^|/)skip(this)?(/|$)

pep8:
  max-line-length: 120

mccabe:
  run: true
  options:
    max-complexity: 7
