Metrics/LineLength:
  Max: 100
Style/RegexpLiteral:
  EnforcedStyle: mixed
  # slashes: Always use slashes.
  # percent_r: Always use %r.
  # mixed: Use slashes on single-line regexes, and %r on multi-line regexes.
  SupportedStyles:
    - slashes
    - percent_r
    - mixed
Lint/Debugger:
  Severity: error
AllCops:
  Exclude:
    - 'db/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
